name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@6f2dee689a9d21f44f1cbe66deb8f6777871ab8e # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'
