name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@6f2dee689a9d21f44f1cbe66deb8f6777871ab8e # pinned to latest
    secrets: inherit
